server:
  port: 9093

spring:
  application:
    name: POSTS-SERVICE

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: eclient, db

  datasource:
    url: jdbc:postgresql://212.118.40.85:5432/sparks_posts
