server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: eclient

  # services-mapping
  cloud:
    gateway:
      routes:
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: POSTS-SERVICE
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/posts/**